## Challenge #2: Preparing Delimited Data

>We hope you enjoyed last week's challenge. The solution has been posted here. For the second challenge lets look at removing characters and splitting data into columns based on delimiters.

>Many products will export textual data with delimiters such as quotes. This is done so that strings can contain delimiters or control characters within them. Having more than one type of delimiter can be hard for ETL programs to interpret.  In the input text file, there are two different delimiters (double quotes, single quotes) and they surround different data types.

>Use Alteryx to **strip out the delimiters as superfluous and format the data as represented in the output.**

>You may notice that we have started classifying the exercises into beginner, Intermediate and advanced.  This classification is used by Alteryx internally to sequence exercises as users advance.

In [1]:
import pandas as pd

In [2]:
# preview output
output = pd.read_csv('output.csv', index_col = False)
df_output = pd.DataFrame(output)
df_output

                                                Poem  Poem_ID Poem_Read_Date
0  Mary had a little lamb whose fleece was white ...      123     2001-06-16
1                   I do not like green eggs and ham      456     2010-12-25

In [3]:
input = pd.read_csv('input.csv', index_col = False)
df = pd.DataFrame(input)
df

                                             Field_1
0  "Mary had a little lamb whose fleece was white...
1  "I do not like green eggs and ham",456,'25-DEC...

In [ ]:
# splits Field_1 column on commas
df[['F1', 'F2', 'F3']] = df['Field_1'].str.split(',', expand=True)
df

,Field_1,F1,F2,F3
0,"""Mary had a little lamb whose fleece was white...","""Mary had a little lamb whose fleece was white...",123,'16-JUN-01'
1,"""I do not like green eggs and ham"",456,'25-DEC...","""I do not like green eggs and ham""",456,'25-DEC-10'

In [ ]:
# replace apostrophes
df['F1'] = df['F1'].str.replace("[\'\"]", "", case=False, regex=True)
df['F3'] = df['F3'].str.replace("[\'\"]", "", case=False, regex=True)
df

,Field_1,F1,F2,F3
0,"""Mary had a little lamb whose fleece was white...",Mary had a little lamb whose fleece was white ...,123,16-JUN-01
1,"""I do not like green eggs and ham"",456,'25-DEC...",I do not like green eggs and ham,456,25-DEC-10

[strftime cheatsheet](https://www.bairesdev.com/tools/strftime/])

In [15]:
# convert to date
pd.to_datetime(df['F3'], format='%d-%b-%y')

0   2001-06-16
1   2010-12-25
Name: F3, dtype: datetime64[ns]